services:
  web:
    build:
      context: ..
      args:
        BUILD: mssql
    restart: unless-stopped
    environment:
      - DB_EXTERNAL=true
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/opt/prod_static

  db:
    image: mcr.microsoft.com/mssql/server
    restart: unless-stopped
    environment:
      MSSQL_PID: "Express"
      MSSQL_SA_PASSWORD: "${DB_PASSWORD:-P@ssw0rd!}"
      ACCEPT_EULA: "Y"
      SQLCMDPASSWORD: "${DB_PASSWORD:-P@ssw0rd!}"
    healthcheck:
      test: /opt/mssql-tools*/bin/sqlcmd -C -S localhost -U sa -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      retries: 10
      timeout: 3s
      start_period: 20s
    volumes:
      - ./init.sql:/init/init.sql
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
      #- /var/opt/mssql:/var/opt/mssql
    entrypoint: ["sh", "/usr/local/bin/entrypoint.sh"]

  nginx:
    build: .
    restart: unless-stopped
    ports:
      - 8000:80
    depends_on:
      - web
    volumes:
      - static:/opt/prod_static

volumes:
  static:
