# Generated by Django 4.2.12 on 2024-09-23 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('viewed', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
    ]
