name: CI - app

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'Dockerfile'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install app dependencies
        run: pip install -r app/requirements.txt

      - name: Run tests
        run: python manage.py test
        working-directory: app
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          IMAGE=filipmania/urlshortener

          docker build -t ${IMAGE}:${GITHUB_RUN_ID} -t ${IMAGE}:latest .
          docker push ${IMAGE}:${GITHUB_RUN_ID}
          docker push ${IMAGE}:latest

          docker build --build-arg BUILD=mssql -t ${IMAGE}:${GITHUB_RUN_ID}-mssql -t ${IMAGE}:mssql .
          docker push ${IMAGE}:${GITHUB_RUN_ID}-mssql
          docker push ${IMAGE}:mssql

          docker build --build-arg BUILD=nginx -t ${IMAGE}:${GITHUB_RUN_ID}-nginx -t ${IMAGE}:nginx .
          docker push ${IMAGE}:${GITHUB_RUN_ID}-nginx
          docker push ${IMAGE}:nginx

      - name: Save the IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_RUN_ID}"
