name: CI - code

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'cdktf/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install test dependencies
        run: pip install flake8

      - name: Lint code
        run: flake8 --extend-ignore=E501
